import { Component } from '@angular/core';
import { CommonModule } from '@angular/common'; // Often needed, import just in case
// Import the standalone component directly because it's used in the template
import { ContactListComponent } from './components/contact-list/contact-list.component';
// If using routing, import RouterOutlet
// import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root', // CSS selector for using this component
  standalone: true, // Mark AppComponent as standalone
  imports: [
    CommonModule, // Good practice to include
    ContactListComponent // Import the component used in the template
    // RouterOutlet // Include if using routing
  ],
  templateUrl: './app.component.html', // Link to the HTML template
  styleUrls: ['./app.component.scss'] // Link to component-specific styles (or .css)
})
export class AppComponent {
  // Component properties (example)
  title = 'contact-app'; // Default property generated by Angular CLI
}